/* This file is automatically generated by the "npm run watch" command. Do not edit! */ 
export default { 
 airport: "_airport",
city: "_city",
country: "_country",
fromCity: "_fromCity",
tickets: "_tickets",
toCity: "_toCity",
}